# #
# kzarshenas/crazy_demo
#
 # Crazy Php Demo website
#
# @author     kekefreedog &lt;kevin.zarshenas@gmail.com&gt;
# @copyright  2024 kzarshenas/crazy_demo
# #
App:
    name: kzarshenas/crazy_demo
    description: 'Crazy Php Demo website'
    type: application
    homepage: 'https://github.com/kekefreedog/CrazyPHP/'
    authors:
        -
            name: kzarshenas
            email: kevin.zarshenas@gmail.com
    autoload:
        psr-4:
            App\:
                - app\/
    require:
        kzarshenas/crazyphp: '@dev'
    repositories:
        -
            type: path
            url: ./../CrazyPHP
            options:
                symlink: true
    root: .
    framework:
        path: ./vendor/kzarshenas/crazyphp
    public: public
    dependencies:
        php:
            packages:
                - git
    local:
        npm: true
