Front:
    lastBuild:
        files:
            - index.b56744d1.js
            - vendors.b56744d1.js
            - runtime.b56744d1.js
        hash: b56744d1
        watch: false
        date: '2025-01-22T23:33:11+00:00'
        pages:
            - Progressbar.b56744d1.js
            - Home.b56744d1.js
            - Index.b56744d1.js
            - Button.b56744d1.js
            - Form.b56744d1.js
