Front:
    lastBuild:
        files:
            - vendors.5eee061a.js
            - index.5eee061a.js
            - runtime.5eee061a.js
        hash: 5eee061a
        watch: false
        date: '2024-11-17T16:28:23+00:00'
        pages:
            - Index.5eee061a.js
            - Form.5eee061a.js
            - Button.5eee061a.js
            - Home.5eee061a.js
            - Progressbar.5eee061a.js
