Front:
    lastBuild:
        files:
            - runtime.6fd46337.js
            - vendors.6fd46337.js
            - index.6fd46337.js
        hash: 6fd46337
        watch: false
        date: '2024-10-29T23:26:35+00:00'
        pages:
            - Form.6fd46337.js
            - Button.6fd46337.js
            - Index.6fd46337.js
            - Home.6fd46337.js
            - Progressbar.6fd46337.js
