Front:
    lastBuild:
        files:
            - runtime.14faf0f0.js
            - vendors.14faf0f0.js
            - index.14faf0f0.js
        hash: 14faf0f0
        watch: false
        date: '2024-12-01T12:41:17+00:00'
        pages:
            - Form.14faf0f0.js
            - Button.14faf0f0.js
            - Index.14faf0f0.js
            - Home.14faf0f0.js
            - Progressbar.14faf0f0.js
