Front:
    lastBuild:
        files:
            - index.40597a3a.js
            - vendors.40597a3a.js
            - runtime.40597a3a.js
        hash: 40597a3a
        watch: false
        date: '2024-11-13T23:11:35+00:00'
        pages:
            - Index.40597a3a.js
            - Form.40597a3a.js
            - Button.40597a3a.js
            - Home.40597a3a.js
            - Progressbar.40597a3a.js
