Front:
    lastBuild:
        files:
            - runtime.238f8d3d.js
            - vendors.238f8d3d.js
            - index.238f8d3d.js
        hash: 238f8d3d
        watch: false
        date: '2024-12-25T23:21:18+00:00'
        pages:
            - Progressbar.238f8d3d.js
            - Home.238f8d3d.js
            - Button.238f8d3d.js
            - Form.238f8d3d.js
            - Index.238f8d3d.js
