Front:
    lastBuild:
        files:
            - index.8712917e.js
            - vendors.8712917e.js
            - runtime.8712917e.js
        hash: 8712917e
        watch: false
        date: '2025-05-11T17:23:32+00:00'
        pages:
            - Home.8712917e.js
            - Request.8712917e.js
            - Progressbar.8712917e.js
            - Index.8712917e.js
            - Form.8712917e.js
            - Button.8712917e.js
