Front:
    lastBuild:
        files:
            - index.00883269.js
            - vendors.00883269.js
            - runtime.00883269.js
        hash: '00883269'
        watch: false
        date: '2024-11-21T23:07:47+00:00'
        pages:
            - Index.00883269.js
            - Form.00883269.js
            - Button.00883269.js
            - Home.00883269.js
            - Progressbar.00883269.js
