Front:
    lastBuild:
        files:
            - runtime.59f436eb.js
            - index.59f436eb.js
            - vendors.59f436eb.js
        hash: 59f436eb
        watch: false
        date: '2024-12-26T17:56:07+00:00'
        pages:
            - Progressbar.59f436eb.js
            - Home.59f436eb.js
            - Button.59f436eb.js
            - Form.59f436eb.js
            - Index.59f436eb.js
