Front:
    lastBuild:
        files:
            - runtime.41de2921.js
            - vendors.41de2921.js
            - index.41de2921.js
        hash: 41de2921
        watch: false
        date: '2024-12-28T19:27:54+00:00'
        pages:
            - Button.41de2921.js
            - Form.41de2921.js
            - Index.41de2921.js
            - Progressbar.41de2921.js
            - Home.41de2921.js
