Front:
    lastBuild:
        files:
            - vendors.c17e8344.js
            - index.c17e8344.js
            - runtime.c17e8344.js
        hash: c17e8344
        watch: false
        date: '2026-08-15T10:02:33+00:00'
        pages:
            - Filter.c17e8344.js
            - Home.c17e8344.js
            - Request.c17e8344.js
            - Progressbar.c17e8344.js
            - Index.c17e8344.js
            - Form.c17e8344.js
            - Button.c17e8344.js
        mode: production
