Front:
    lastBuild:
        files:
            - index.da18aef4.js
            - vendors.da18aef4.js
            - runtime.da18aef4.js
        hash: da18aef4
        watch: false
        date: '2025-02-12T21:10:49+00:00'
        pages:
            - Index.da18aef4.js
            - Form.da18aef4.js
            - Button.da18aef4.js
            - Home.da18aef4.js
            - Progressbar.da18aef4.js
