Front:
    lastBuild:
        files:
            - vendors.a1ba4c84.js
            - index.a1ba4c84.js
            - runtime.a1ba4c84.js
        hash: a1ba4c84
        watch: true
        date: '2024-11-10T16:07:47+00:00'
        pages:
            - Index.a1ba4c84.js
            - Form.a1ba4c84.js
            - Button.a1ba4c84.js
            - Home.a1ba4c84.js
            - Progressbar.a1ba4c84.js
