Front:
    lastBuild:
        files:
            - runtime.8df267dc.js
            - index.8df267dc.js
            - vendors.8df267dc.js
        hash: 8df267dc
        watch: false
        date: '2024-12-19T00:20:17+00:00'
        pages:
            - Button.8df267dc.js
            - Form.8df267dc.js
            - Index.8df267dc.js
            - Progressbar.8df267dc.js
            - Home.8df267dc.js
