Front:
    lastBuild:
        files:
            - index.d92ae1d1.js
            - vendors.d92ae1d1.js
            - runtime.d92ae1d1.js
        hash: d92ae1d1
        watch: false
        date: '2025-05-10T08:36:26+00:00'
        pages:
            - Index.d92ae1d1.js
            - Form.d92ae1d1.js
            - Button.d92ae1d1.js
            - Home.d92ae1d1.js
            - Progressbar.d92ae1d1.js
            - Request.d92ae1d1.js
