Front:
    lastBuild:
        files:
            - runtime.2be50a14.js
            - vendors.2be50a14.js
            - index.2be50a14.js
        hash: 2be50a14
        watch: false
        date: '2025-07-12T19:26:38+00:00'
        pages:
            - Request.2be50a14.js
            - Progressbar.2be50a14.js
            - Home.2be50a14.js
            - Button.2be50a14.js
            - Form.2be50a14.js
            - Index.2be50a14.js
