Front:
    lastBuild:
        files:
            - vendors.b66e0bdf.js
            - index.b66e0bdf.js
            - runtime.b66e0bdf.js
        hash: b66e0bdf
        watch: false
        date: '2026-08-15T11:51:50+00:00'
        pages:
            - Index.b66e0bdf.js
            - Form.b66e0bdf.js
            - Button.b66e0bdf.js
            - Filter.b66e0bdf.js
            - Home.b66e0bdf.js
            - Progressbar.b66e0bdf.js
            - Request.b66e0bdf.js
        mode: production
