Front:
    lastBuild:
        files:
            - vendors.67e72539.js
            - index.67e72539.js
            - runtime.67e72539.js
        hash: '67e72539'
        watch: false
        date: '2025-03-23T13:38:28+00:00'
        pages:
            - Index.67e72539.js
            - Button.67e72539.js
            - Form.67e72539.js
            - Progressbar.67e72539.js
            - Home.67e72539.js
