Front:
    lastBuild:
        files:
            - runtime.229de747.js
            - vendors.229de747.js
            - index.229de747.js
        hash: 229de747
        watch: false
        date: '2025-05-11T16:43:15+00:00'
        pages:
            - Form.229de747.js
            - Button.229de747.js
            - Index.229de747.js
            - Home.229de747.js
            - Progressbar.229de747.js
            - Request.229de747.js
