Front:
    lastBuild:
        files:
            - runtime.a390010f.js
            - index.a390010f.js
            - vendors.a390010f.js
        hash: a390010f
        watch: false
        date: '2024-12-25T16:45:04+00:00'
        pages:
            - Progressbar.a390010f.js
            - Home.a390010f.js
            - Button.a390010f.js
            - Form.a390010f.js
            - Index.a390010f.js
