Front:
    lastBuild:
        files:
            - vendors.8eec58a4.js
            - index.8eec58a4.js
            - runtime.8eec58a4.js
        hash: 8eec58a4
        watch: false
        date: '2025-05-11T16:46:24+00:00'
        pages:
            - Index.8eec58a4.js
            - Form.8eec58a4.js
            - Button.8eec58a4.js
            - Home.8eec58a4.js
            - Progressbar.8eec58a4.js
            - Request.8eec58a4.js
