Front:
    lastBuild:
        files:
            - runtime.230fb05e.js
            - vendors.230fb05e.js
            - index.230fb05e.js
        hash: 230fb05e
        watch: false
        date: '2024-11-11T13:45:49+00:00'
        pages:
            - Form.230fb05e.js
            - Button.230fb05e.js
            - Index.230fb05e.js
            - Home.230fb05e.js
            - Progressbar.230fb05e.js
