Front:
    lastBuild:
        files:
            - runtime.b062b9ce.js
            - vendors.b062b9ce.js
            - index.b062b9ce.js
        hash: b062b9ce
        watch: false
        date: '2024-12-24T23:51:37+00:00'
        pages:
            - Progressbar.b062b9ce.js
            - Home.b062b9ce.js
            - Button.b062b9ce.js
            - Form.b062b9ce.js
            - Index.b062b9ce.js
